---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: jenkins-test
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins-test
  replicas: 1 
  template: 
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
      - name: jenkins-test
        image: kjin17/jenkinstest:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-test
  namespace: default
  labels:
    app: jenkins-test
spec:
  ports:
  - name: http 
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jenkins-test
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx 
  name: jenkinstest-ingress
  namespace: default
spec:
  rules:
  - host: jenkinstest.localhost
    http:
      paths:
      - backend:
          service:
            name: jenkinstest
            port:
              name: http
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: localhost
